-- Add missing columns used by the unidades module
ALTER TABLE unidades
  ADD COLUMN IF NOT EXISTS instituicao_id UUID,
  ADD COLUMN IF NOT EXISTS instituicao_nome VARCHAR(255),
  ADD COLUMN IF NOT EXISTS numero VARCHAR(50),
  ADD COLUMN IF NOT EXISTS bairro VARCHAR(100),
  ADD COLUMN IF NOT EXISTS local VARCHAR(255),
  ADD COLUMN IF NOT EXISTS codigo_polo_recenseamento VARCHAR(100),
  ADD COLUMN IF NOT EXISTS instituicao_ensino_superior BOOLEAN DEFAULT false,
  ADD COLUMN IF NOT EXISTS situacao VARCHAR(20) DEFAULT 'ATIVO',
  ADD COLUMN IF NOT EXISTS cod_mec_mantenedora VARCHAR(50),
  ADD COLUMN IF NOT EXISTS cnpj_mantenedora VARCHAR(18),
  ADD COLUMN IF NOT EXISTS razao_social VARCHAR(255),
  ADD COLUMN IF NOT EXISTS cep_mantenedora VARCHAR(10),
  ADD COLUMN IF NOT EXISTS logradouro_mantenedora VARCHAR(255),
  ADD COLUMN IF NOT EXISTS numero_mantenedora VARCHAR(50),
  ADD COLUMN IF NOT EXISTS complemento_mantenedora VARCHAR(255),
  ADD COLUMN IF NOT EXISTS bairro_mantenedora VARCHAR(100),
  ADD COLUMN IF NOT EXISTS uf_mantenedora CHAR(2),
  ADD COLUMN IF NOT EXISTS tipo_credenciamento VARCHAR(100),
  ADD COLUMN IF NOT EXISTS numero_credenciamento VARCHAR(100),
  ADD COLUMN IF NOT EXISTS data_credenciamento DATE,
  ADD COLUMN IF NOT EXISTS veiculo_publicacao VARCHAR(255),
  ADD COLUMN IF NOT EXISTS data_publicacao DATE,
  ADD COLUMN IF NOT EXISTS secao_publicacao VARCHAR(50),
  ADD COLUMN IF NOT EXISTS pagina_publicacao VARCHAR(50),
  ADD COLUMN IF NOT EXISTS numero_dou VARCHAR(50),
  ADD COLUMN IF NOT EXISTS tem_recredenciamento BOOLEAN DEFAULT false,
  ADD COLUMN IF NOT EXISTS tipo_recredenciamento VARCHAR(100),
  ADD COLUMN IF NOT EXISTS numero_recredenciamento VARCHAR(100),
  ADD COLUMN IF NOT EXISTS data_recredenciamento DATE,
  ADD COLUMN IF NOT EXISTS veiculo_recredenciamento VARCHAR(255),
  ADD COLUMN IF NOT EXISTS data_publicacao_recredenciamento DATE,
  ADD COLUMN IF NOT EXISTS secao_recredenciamento VARCHAR(50),
  ADD COLUMN IF NOT EXISTS pagina_recredenciamento VARCHAR(50),
  ADD COLUMN IF NOT EXISTS numero_dou_recredenciamento VARCHAR(50),
  ADD COLUMN IF NOT EXISTS numero_processo_recredenciamento VARCHAR(100),
  ADD COLUMN IF NOT EXISTS tipo_processo_recredenciamento VARCHAR(100),
  ADD COLUMN IF NOT EXISTS data_cadastro_recredenciamento DATE,
  ADD COLUMN IF NOT EXISTS data_protocolo_recredenciamento DATE,
  ADD COLUMN IF NOT EXISTS tem_renovacao BOOLEAN DEFAULT false,
  ADD COLUMN IF NOT EXISTS tipo_renovacao VARCHAR(100),
  ADD COLUMN IF NOT EXISTS numero_renovacao VARCHAR(100),
  ADD COLUMN IF NOT EXISTS data_renovacao DATE,
  ADD COLUMN IF NOT EXISTS veiculo_renovacao VARCHAR(255),
  ADD COLUMN IF NOT EXISTS data_publicacao_renovacao DATE,
  ADD COLUMN IF NOT EXISTS secao_renovacao VARCHAR(50),
  ADD COLUMN IF NOT EXISTS pagina_renovacao VARCHAR(50),
  ADD COLUMN IF NOT EXISTS numero_dou_renovacao VARCHAR(50),
  ADD COLUMN IF NOT EXISTS numero_processo_renovacao VARCHAR(100),
  ADD COLUMN IF NOT EXISTS tipo_processo_renovacao VARCHAR(100),
  ADD COLUMN IF NOT EXISTS data_cadastro_renovacao DATE,
  ADD COLUMN IF NOT EXISTS data_protocolo_renovacao DATE,
  ADD COLUMN IF NOT EXISTS cursos INTEGER[];
